/**
 * Tanzer Anderson Daily Briefing source adapter.
 *
 * Purpose:
 * - Build Henry and Destiny briefing payloads from a governed Google Sheet.
 * - Add verified calendar events.
 * - Push both payloads to the independent Cloudflare Worker before 7:15 AM CT.
 *
 * Required Script Properties:
 * - WORKER_SOURCE_URL: https://<worker>.workers.dev
 * - WORKER_SOURCE_PUSH_SECRET: value matching the Worker's SOURCE_PUSH_SECRET
 *
 * Optional Script Properties:
 * - BRIEFING_CONTROL_SHEET_ID: generated by installDailyBriefingSource()
 * - DESTINY_CALENDAR_ID: coordinator calendar ID; Henry's calendar is never copied to Destiny by default.
 */

const TA_TIME_ZONE = 'America/Chicago';
const TA_HEADERS = ['Audience', 'Section', 'Text', 'Status', 'DueDate', 'RequiresApproval', 'AutomationSafe', 'ExecutionKey', 'Owner', 'Detail'];

function installDailyBriefingSource() {
  const props = PropertiesService.getScriptProperties();
  let sheetId = props.getProperty('BRIEFING_CONTROL_SHEET_ID');
  let spreadsheet;
  if (sheetId) {
    spreadsheet = SpreadsheetApp.openById(sheetId);
  } else {
    spreadsheet = SpreadsheetApp.create('Tanzer Anderson | Daily Briefing Control');
    sheetId = spreadsheet.getId();
    props.setProperty('BRIEFING_CONTROL_SHEET_ID', sheetId);
  }

  let sheet = spreadsheet.getSheetByName('Briefing Items');
  if (!sheet) sheet = spreadsheet.insertSheet('Briefing Items');
  sheet.clear();
  sheet.getRange(1, 1, 1, TA_HEADERS.length).setValues([TA_HEADERS]);
  sheet.getRange(2, 1, 8, TA_HEADERS.length).setValues([
    ['henry', 'priority', 'Review the highest-consequence decision queue', 'active', '', false, false, '', 'Henry', ''],
    ['henry', 'priority', 'Protect client delivery and candidate-response capacity', 'active', '', false, false, '', 'Henry', ''],
    ['henry', 'decision', 'Maintain the external-outreach hold until wrapped-email QA passes', 'active', '', true, true, 'outreach.hold', 'Henry', ''],
    ['henry', 'action', 'Review the independent briefing and approval controls', 'active', '', true, false, '', 'Henry', ''],
    ['henry', 'risk', 'Do not treat stale or unverified data as a live commitment', 'active', '', false, false, '', 'System', ''],
    ['destiny', 'priority', 'Review the coordinator queue and surface decisions for Henry', 'active', '', false, false, '', 'Destiny', ''],
    ['destiny', 'decision', 'Keep external outreach on hold until Henry releases the wrapped-email standard', 'active', '', true, true, 'outreach.hold', 'Destiny', ''],
    ['destiny', 'action', 'Complete the morning coordinator queue review', 'active', '', true, false, '', 'Destiny', ''],
  ]);
  sheet.setFrozenRows(1);
  sheet.autoResizeColumns(1, TA_HEADERS.length);

  ScriptApp.getProjectTriggers()
    .filter((trigger) => trigger.getHandlerFunction() === 'publishDailyBriefings')
    .forEach((trigger) => ScriptApp.deleteTrigger(trigger));

  ScriptApp.newTrigger('publishDailyBriefings')
    .timeBased()
    .atHour(6)
    .nearMinute(45)
    .everyDays(1)
    .inTimezone(TA_TIME_ZONE)
    .create();

  return {
    spreadsheetUrl: spreadsheet.getUrl(),
    trigger: 'Daily near 6:45 AM America/Chicago',
    next: 'Set WORKER_SOURCE_URL and WORKER_SOURCE_PUSH_SECRET in Script Properties, then run publishDailyBriefings once.',
  };
}

function publishDailyBriefings() {
  const props = PropertiesService.getScriptProperties();
  const workerUrl = String(props.getProperty('WORKER_SOURCE_URL') || '').replace(/\/$/, '');
  const secret = props.getProperty('WORKER_SOURCE_PUSH_SECRET');
  if (!workerUrl || !secret) throw new Error('WORKER_SOURCE_URL and WORKER_SOURCE_PUSH_SECRET are required Script Properties.');

  const now = new Date();
  const dateKey = Utilities.formatDate(now, TA_TIME_ZONE, 'yyyy-MM-dd');
  const briefings = [buildBriefing_('henry', dateKey), buildBriefing_('destiny', dateKey)];
  const response = UrlFetchApp.fetch(workerUrl + '/api/source/push', {
    method: 'post',
    contentType: 'application/json',
    headers: { Authorization: 'Bearer ' + secret },
    payload: JSON.stringify({ briefings: briefings }),
    muteHttpExceptions: true,
  });
  const status = response.getResponseCode();
  if (status < 200 || status >= 300) throw new Error('Worker source push failed: HTTP ' + status + ' ' + response.getContentText());
  return JSON.parse(response.getContentText());
}

function buildBriefing_(audience, dateKey) {
  const rows = readBriefingRows_(audience, dateKey);
  const meetings = readMeetings_(audience, dateKey);
  return {
    audience: audience,
    dateKey: dateKey,
    title: audience === 'destiny' ? 'Daily Coordinator Briefing' : 'Daily Executive Briefing',
    summary: audience === 'destiny'
      ? 'Coordinator priorities, verified meetings, decision gates, and follow-through for the operating day.'
      : 'Decision-ready priorities, verified meetings, material risks, and approval-controlled next actions for the operating day.',
    sourceLabel: 'Google Workspace governed source adapter',
    sourceStatus: 'live-pushed',
    topPriorities: rows.priority,
    decisions: rows.decision,
    meetings: meetings,
    risks: rows.risk,
    nextActions: rows.action,
  };
}

function readBriefingRows_(audience, dateKey) {
  const props = PropertiesService.getScriptProperties();
  const sheetId = props.getProperty('BRIEFING_CONTROL_SHEET_ID');
  if (!sheetId) throw new Error('Run installDailyBriefingSource() first.');
  const sheet = SpreadsheetApp.openById(sheetId).getSheetByName('Briefing Items');
  if (!sheet) throw new Error('Briefing Items sheet is missing.');

  const values = sheet.getDataRange().getValues();
  const headers = values.shift().map(String);
  const index = Object.fromEntries(headers.map((header, i) => [header, i]));
  const result = { priority: [], decision: [], risk: [], action: [] };

  values.forEach((row, rowIndex) => {
    const rowAudience = String(row[index.Audience] || '').toLowerCase().trim();
    const section = String(row[index.Section] || '').toLowerCase().trim();
    const text = String(row[index.Text] || '').trim();
    const status = String(row[index.Status] || 'active').toLowerCase().trim();
    const dueDate = normalizeDate_(row[index.DueDate]);
    if (rowAudience !== audience || !result[section] || !text || status !== 'active') return;
    if (dueDate && dueDate !== dateKey) return;

    result[section].push({
      id: section + '-' + (rowIndex + 2) + '-' + text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 48),
      text: text,
      detail: String(row[index.Detail] || '').trim(),
      requiresApproval: toBoolean_(row[index.RequiresApproval]),
      automationSafe: toBoolean_(row[index.AutomationSafe]),
      executionKey: String(row[index.ExecutionKey] || '').trim(),
      owner: String(row[index.Owner] || '').trim(),
      due: dueDate,
    });
  });
  return result;
}

function readMeetings_(audience, dateKey) {
  let calendar;
  if (audience === 'henry') {
    calendar = CalendarApp.getDefaultCalendar();
  } else {
    const id = PropertiesService.getScriptProperties().getProperty('DESTINY_CALENDAR_ID');
    if (!id) return [];
    calendar = CalendarApp.getCalendarById(id);
    if (!calendar) return [];
  }

  const day = new Date(dateKey + 'T12:00:00');
  return calendar.getEventsForDay(day).map((event) => ({
    time: event.isAllDayEvent() ? 'ALL DAY' : Utilities.formatDate(event.getStartTime(), TA_TIME_ZONE, 'h:mm a'),
    title: event.getTitle(),
  }));
}

function normalizeDate_(value) {
  if (!value) return '';
  if (Object.prototype.toString.call(value) === '[object Date]' && !isNaN(value)) {
    return Utilities.formatDate(value, TA_TIME_ZONE, 'yyyy-MM-dd');
  }
  const text = String(value).trim();
  return /^\d{4}-\d{2}-\d{2}$/.test(text) ? text : '';
}

function toBoolean_(value) {
  if (value === true || value === 1) return true;
  return ['true', 'yes', 'y', '1'].indexOf(String(value).toLowerCase().trim()) >= 0;
}
